gharsewa/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('admins/', include('admins.urls')),
    path('services/', include('services.urls')),
    path('users/', include('users.urls'))
]

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('get_category', views.get_category, name='get_category'),
    path('category_form', views.category_form, name='category_form'),
    path('delete_category/<int:category_id>', views.delete_category, name="delete_category"),
    path('update_category/<int:category_id>', views.update_category,name='update_category'),
    path('get_category_services/<int:category_id>', views.get_category_services,name='get_category_services'),

    path('service_form', views.service_form,name='service_form'),
    path('get_service', views.get_service, name="get_service"),
    path('delete_service/<int:service_id>', views.delete_service, name='delete_service'),
    path('update_service/<int:service_id>', views.update_service, name='update_service'),

    path('get_appointment', views.get_appointment, name='get_appointment'),
    path('delete_appointment/<int:appointment_id>', views.delete_appointment),
    path('update_appointment_status/<int:appointment_id>', views.update_appointment_status),

    path('show_categories', views.show_categories, name="show_categories"),
    path('show_category_services/<int:category_id>', views.show_category_services),

    ]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('post_feedback/<int:category_id>', views.post_feedback,name='post_feedback'),

    path('add_to_wishlist/<int:service_id>/<int:category_id>', views.add_to_wishlist,name='add_to_wishlist'),
    path('my_wishlist', views.show_wishlist_services,name='show_wishlist_services'),
    path('remove_wishlist_service/<int:wishlist_id>', views.remove_wishlist_item,name='remove_wishlist_item'),

    path('appointment_form/<int:service_id>/<int:wishlist_id>', views.appointment_form,name='appointment_form'),
    path('my_appointment', views.my_appointment,name='my_appointment'),
]

services/models.py
from django.db import models
from django.core import validators


class Category(models.Model):
    category_name = models.CharField(max_length=200, validators=[validators.MinLengthValidator(2)], null=True)
    description = models.TextField()
    added_date = models.DateTimeField(auto_now_add=True)
    image = models.FileField(upload_to='static/uploads/category-images', null=True)

    def __str__(self):
        return self.category_name


class Service(models.Model):
    service_name = models.CharField(max_length=200, validators=[validators.MinLengthValidator(2)], null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    service_description = models.TextField(null=True)
    session_time = models.IntegerField(null=True)
    image = models.FileField(upload_to='static/uploads/service-images', null=True)
    session_cost = models.FloatField(null=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.service_name

services/forms.py
from django import forms
from django.forms import ModelForm
from .models import Service, Category


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = "__all__"


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

services/views.py
import os
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from accounts.auth import admin_only
from users.models import Appointment, Feedback
from .forms import ServiceForm, CategoryForm
from django.contrib import messages
from .models import Service, Category
from .filters import ServiceFilter, CategoryFilter, AppointmentFilter


@login_required
@admin_only
# This function renders the categories page of admin panel with all the categories.
def get_category(request):
    categories = Category.objects.all().order_by('-id')

    category_filter = CategoryFilter(request.GET, queryset=categories)
    category_final = category_filter.qs
    context = {
        'categories': category_final,
        'activate_category': 'active',
        'category_filter': category_filter
    }
    return render(request, 'services/get_category.html', context)


@login_required
@admin_only
# This function allows admin to add categories through category form.
def category_form(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Category added successfully')
            return redirect('/services/get_category')
        else:
            messages.add_message(request, messages.ERROR, 'Something went wrong')
            return render(request, 'accounts/category_form.html', {'form_category': form})
    context = {
        'form_category': CategoryForm,
        'activate_category': 'active'
    }
    return render(request, 'services/category_form.html', context)


@login_required
@admin_only
# This function allows admin to delete a category.
def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    messages.add_message(request, messages.SUCCESS, 'Category deleted successfully')
    return redirect('/services/get_category')


@login_required
@admin_only
# This function allows admin to update category details.
def update_category(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method == "POST":
        form = CategoryForm(request.POST,request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Category updated successfully")
            return redirect("/services/get_category")
        else:
            messages.add_message(request, messages.ERROR, "Unable to update category")
            return redirect(request, "services/category_update_form.html", {'form_category': form})
    context = {
        'form_category': CategoryForm(instance=category),
        'activate_category': 'active'
    }
    return render(request, 'services/category_update_form.html', context)


@login_required
@admin_only
# This function allows admin to view all the added services of the a category.
def get_category_services(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {
        'category': category
    }
    return render(request, 'services/get_category_services.html', context)


@login_required
@admin_only
# This function allows admin to add a service through service category form.
def service_form(request):
    if request.method == "POST":
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Service added successfully')
            return redirect('/services/get_service')
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add service')
            return render(request, 'services/service_form.html', {'form_service': form})
    context = {
        'form_service': ServiceForm,
        'activate_service': 'active'
    }
    return render(request, 'services/service_form.html', context)


@login_required
@admin_only
# This function returns the service page of admin panel consisting of all the added services.
def get_service(request):
    services = Service.objects.all().order_by('-id')
    service_filter = ServiceFilter(request.GET, queryset=services)
    services_final = service_filter.qs
    context = {
        'services': services_final,
        'activate_service': 'active',
        'service_filter': service_filter
    }
    return render(request, 'services/get_service.html', context)


@login_required
@admin_only
# This function allows admin to delete a service.
def delete_service(request, service_id):
    service = Service.objects.get(id=service_id)
    service.delete()
    messages.add_message(request, messages.SUCCESS, 'Service deleted successfully')
    return redirect('/services/get_service')


@login_required
@admin_only
# This function allows admin to update the details of a service.
def update_service(request, service_id):
    service = Service.objects.get(id=service_id)
    if request.method == "POST":
        if request.FILES.get('image'):
            os.remove(service.image.path)
        form = ServiceForm(request.POST, request.FILES, instance=service)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Service updated successfully")
            return redirect("/services/get_service")
        else:
            messages.add_message(request, messages.ERROR, "Unable to update service")
            return redirect(request, "services/service_update_form.html", {'form_service': form})
    context = {
        'form_service': ServiceForm(instance=service),
        'activate_service': 'active'
    }
    return render(request, 'services/service_update_form.html', context)


@login_required
@admin_only
# This function renders the appointment page of admin panel with all the booked appointments.
def get_appointment(request):
    appointments = Appointment.objects.all().order_by('-id')
    appointment_filter = AppointmentFilter(request.GET, queryset=appointments)
    appointment_final = appointment_filter.qs
    context = {
        'appointments': appointment_final,
        'activate_appointment': 'active',
        'appointment_filter': appointment_filter
    }
    return render(request, 'services/get_appointment.html', context)


@login_required
@admin_only
# This function allows admin to delete an appointment.
def delete_appointment(request, appointment_id):
    appointment = Appointment.objects.get(id=appointment_id)
    appointment.delete()
    messages.add_message(request, messages.SUCCESS, 'Appointment deleted successfully')
    return redirect('/services/get_appointment')


@login_required
@admin_only
# This function allows admin to update the status of the appointment.
def update_appointment_status(request, appointment_id):
    appointment = Appointment.objects.get(id=appointment_id)
    appointment.status = "Completed"
    appointment.save()
    messages.add_message(request, messages.SUCCESS, 'Status changed to Completed')
    return redirect('/services/get_appointment')


# This function renders categories page on the user side.
def show_categories(request):
    categories = Category.objects.all().order_by('-id')
    context = {
        'categories': categories,
        'activate_services': 'active'
    }
    return render(request, 'services/show_categories.html', context)


# This function renders the services of a selected category on the user side.
def show_category_services(request, category_id):
    category = Category.objects.get(id=category_id)
    feedback = Feedback.objects.filter(category=category)
    context = {
        'category': category,
        'activate_services': 'active',
        'feedbacks': feedback
    }
    return render(request, 'services/show_category_services.html', context)

services/templates/services/category_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
<title>Add Category</title>
{% endblock %}
{% block main_content %}
<div class="service">
    <h1 class="text-center heading-text">Add Categories</h1>
    <div class="container mb-5 mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% include 'messages.html' %}
                <div class="card form-box-shadow py-4 px-4">
                    <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form_category | bootstrap_horizontal }}
                        <button type="submit" class="btn btn-primary mt-3 ">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder="Enter category name"
    var form_fields2 = document.getElementsByTagName('textarea')
    form_fields2[0].placeholder="Enter description"
    for (field in form_fields){
    form_fields[field].className +=' my-3'
    }
    for (field in form_fields2){
    form_fields2[field].className +=' my-3'
    }



</script>
{% endblock %}

services/templates/services/category_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
<title>Update Category</title>
{% endblock %}
{% block main_content %}
<div class="service">
    <h1 class="text-center heading-text">Update Category</h1>
    <div class="container mb-5 mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                
                {% include 'messages.html' %}
                <div class="card form-box-shadow py-4 px-4">
                    <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form_category | bootstrap_horizontal }}
                        <button type="submit" class="btn btn-primary mt-3 ">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
  var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder="Enter category name"
    var form_fields2 = document.getElementsByTagName('textarea')
    form_fields2[0].placeholder="Enter description"
    for (field in form_fields){
    form_fields[field].className +=' my-3'
    }

     for (field in form_fields2){
    form_fields2[field].className +=' my-3'
    }





</script>
{% endblock %}

services/templates/services/get_appointment.html
{% extends 'layout-admin.html' %} {% load bootstrap %} {% block title %}
<title>All Services</title>
{% endblock %} {% block main_content %}

<h1 class="text-center heading-text">Appointments</h1>
<div class="container mb-5 mt-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      {% include 'messages.html' %}
      <div class="card shadow outer-card py-2 px-2">
        <div class="card card-body">
          <form action="" class="form myForm filter-form mb-3" method="get">
            {{ appointment_filter.form | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary btn-md mt-3 filter-search-btn">
              <i class="fas fa-search"></i> Search
            </button>
          </form>
        </div>
        <div class="table-responsive">
          <table class="table table-striped">
            <tr>
              <th>User</th>
              <th>Service</th>
              <th>
                Session <br />
                (min)
              </th>
              <th>Address</th>
              <th>Contact</th>
              <th>Date</th>
              <th>Cost(Rs.)</th>
              <th>Status</th>
              <!-- <th>Date Added</th> -->
              <th>Actions</th>
            </tr>
            {% for i in appointments %}
            <tr>
              <td class="text-center">{{ i.user.username }}</td>
              <td class="text-center">{{ i.service.service_name }}</td>
              <td class="text-center">{{ i.session_time }}</td>
              <td class="text-justify">{{ i.address }}</td>
              <td class="text-center">{{ i.contact_no }}</td>
              <td class="text-center">{{ i.date }}</td>
              <td class="text-center">{{ i.total_cost }}</td>
              <td class="text-center">{{ i.status }}</td>
              <!-- <td> {{ i.added_date }}</td> -->

              <td class="text-center">
                <a class="btn btn-primary btn-sm mb-2" href="/services/update_appointment_status/{{i.id}}"
                  ><i class="fas fa-marker"></i> Update</a
                >
                <a
                  class="btn btn-danger btn-sm mb-2"
                  href="/services/delete_appointment/{{i.id}}"
                  onclick="return confirm('Are you sure you want to delete this appointment?')"
                  ><i class="fas fa-trash-alt"></i> Delete
                </a>
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

services/templates/services/get_category.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
<title>All Service Categories</title>
{% endblock %}
{% block main_content %}
<h1 class="text-center heading-text">Categories</h1>
<div class="container mb-5 mt-5">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            {% include 'messages.html' %}
            <div class="card shadow outer-card py-2 px-2">
                <a class="btn btn-primary btn-md mb-4 ms-auto" href="/services/category_form"><i
                        class="fas fa-plus"></i> Add New Category</a>
                <div class="card  card-body">
                    <form action="" class="form myForm filter-form mb-3" method="get">
                        {{ category_filter.form | bootstrap_horizontal }}
                        <button type="submit" class="btn btn-primary btn-md mt-3 filter-search-btn"><i
                                class="fas fa-search"></i> Search
                        </button>
                    </form>
                </div>
                <div class="table-responsive">
                    <table class=" table table-striped  ">
                        <tr>
                            <th>Category</th>
                            <th>Description</th>
                            <th>Image</th>
                            <th>Date Added</th>
                            <th>Actions</th>
                        </tr>
                        {% for i in categories %}
                        <tr>
                            <td class="text-center"><a
                                    href="/services/get_category_services/{{i.id}}">{{i.category_name}}</a></td>
                            <td class="text-justify"> {{ i.description }}</td>
                            <td class="text-center"><img src="/{{i.image}}" width="100" height="100"></td>
                            <td> {{ i.added_date }}</td>
                            <td class="text-center"><a class="btn btn-primary btn-sm mb-2"
                                    href="/services/update_category/{{i.id}}"><i class="fas fa-marker"></i> Edit</a>
                                &nbsp;
                                <a class="btn btn-danger btn-sm mb-2" href="/services/delete_category/{{i.id}}"
                                    onclick="return confirm('Are you sure you want to delete this service?')"><i
                                        class="fas fa-trash-alt"></i> Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

services/templates/services/get_category_services.html
{% extends 'layout-admin.html' %}
{% block title %}
<title>Category services</title>
{% endblock title %}
{% block main_content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center text-uppercase mb-5  font-weight-bold">All services of
                {{category.category_name}}</h1>
        </div>
        <div class="col-md-12">
            <div class="row">
                {% for i in category.service_set.all %}
                <div class="col-md-3 mb-3">
                    <div class="card shadow-lg">
                        <img class="card-img-top" src="/{{i.image}}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Service: {{i.service_name}}</h5>
                            <p class="card-text">Description: {{i.service_description}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

services/templates/services/get_service.html
{% extends 'layout-admin.html' %} {% load bootstrap %} {% block title %}
<title>All Services</title>
{% endblock %} {% block main_content %}

<h1 class="text-center heading-text">Services</h1>
<div class="container mb-5 mt-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      {% include 'messages.html' %}
      <div class="card shadow outer-card py-2 px-2">
        <a class="btn btn-primary btn-md mb-4 ms-auto" href="/services/service_form"
          ><i class="fas fa-plus"></i> Add New Service</a
        >
        <div class="card card-body">
          <form action="" class="form myForm filter-form mb-3" method="get">
            {{ service_filter.form | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary btn-md mt-3 filter-search-btn">
              <i class="fas fa-search"></i> Search
            </button>
          </form>
        </div>
        <div class="table-responsive">
          <table class="table table-striped">
            <tr>
              <th>Service</th>
              <th>Category</th>
              <th>Description</th>
              <th>
                Session <br />
                (min)
              </th>
              <th>Image</th>
              <th>Cost(Rs.)</th>
              <!-- <th>Date Added</th> -->
              <th>Actions</th>
            </tr>
            {% for i in services %}
            <tr>
              <td class="text-center">{{ i.service_name }}</td>
              <td class="text-center">{{ i.category }}</td>
              <td class="text-justify">{{ i.service_description }}</td>
              <td class="text-center">{{ i.session_time }}</td>
              <td class="text-center"><img src="/{{i.image}}" width="100" height="100" /></td>
              <td class="text-center">{{ i.session_cost }}</td>
              <!-- <td> {{ i.added_date }}</td> -->

              <td class="text-center">
                <a class="btn btn-primary btn-sm mb-2" href="/services/update_service/{{i.id}}"
                  ><i class="fas fa-marker"></i> Edit</a
                >
                &nbsp;
                <a
                  class="btn btn-danger btn-sm mb-2"
                  href="/services/delete_service/{{i.id}}"
                  onclick="return confirm('Are you sure you want to delete this service?')"
                  ><i class="fas fa-trash-alt"></i> Delete</a
                >
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

services/templates/services/service_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
<title>Add Service</title>
{% endblock %}
{% block main_content %}
<div class="service">
    <h1 class="text-center heading-text">Add Services</h1>
    <div class="container mb-5 mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% include 'messages.html' %}
                <div class="card form-box-shadow py-4 px-4">
                    <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form_service | bootstrap_horizontal }}
                        <button type="submit" class="btn btn-primary mt-3 ">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder="Enter service name"
    form_fields[2].placeholder= "Enter session time"
    form_fields[4].placeholder= "Enter session cost"
    var form_fields2 = document.getElementsByTagName('textarea')
    var form_fields3 = document.getElementsByTagName('select')
    form_fields2[0].placeholder="Enter description"
    for (field in form_fields){
    form_fields[field].className +=' my-3'
    }
     for (field in form_fields2){
    form_fields2[field].className +=' my-3'
    }
      for (field in form_fields3){
    form_fields3[field].className +=' my-3'
    }
</script>


{% endblock %}

services/templates/services/service_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
<title>Update Service</title>
{% endblock %}
{% block main_content %}
<div class="service">
    <h1 class="text-center heading-text">Update Service</h1>
    <div class="container mb-5 mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">

                {% include 'messages.html' %}
                <div class="card form-box-shadow py-4 px-4">
                    <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form_service | bootstrap_horizontal }}
                        <button type="submit" class="btn btn-primary mt-3 ">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var form_fields = document.getElementsByTagName('input')
    var form_fields2 = document.getElementsByTagName('textarea')
    var form_fields3 = document.getElementsByTagName('select')
    form_fields[1].placeholder="Enter service name"
    form_fields[2].placeholder= "Enter session time"
    form_fields[4].placeholder= "Enter session cost"
    form_fields2[0].placeholder="Enter description"

    for (field in form_fields){
    form_fields[field].className +=' my-3'
    }

     for (field in form_fields2){
    form_fields2[field].className +=' my-3'
    }

       for (field in form_fields3){
    form_fields3[field].className +=' my-3'
    }
</script>
{% endblock %}

services/templates/services/show_categories.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
<title>Services</title>
{% endblock title %}
{% block main_content %}
<link rel="stylesheet" href="{% static 'css/services.css' %}">
<div class="category-container">
<section class="category-showcase-section" id="services">
    <h3 class="category-showcase-text" data-aos="flip-down"  data-aos-delay="50"
    data-aos-duration="1000">Select Category</h3>
    <div class="category-showcase">
        {% for i in categories %}
        <a href="/services/show_category_services/{{i.id}}" data-aos="fade-up"  data-aos-delay="50"
    data-aos-duration="1000" >
            <div class="category-card">
                <img src="/{{i.image}}" alt="">
                <p class="category-card-label">{{i.category_name}}</p>
            </div>
        </a>
        {% endfor %}
    </div>
</section>
</div>
{% endblock main_content %}

services/templates/services/show_category_services.html
{% extends 'layout.html' %}
{% block title %}
{% load static %}
<title>Category services</title>
{% endblock title %}
{% block main_content %}
<link rel="stylesheet" href="{% static 'css/services.css' %}">
<h1 class="head-text text-center  mt-5 mb-5" data-aos="fade-down"
    data-aos-duration="500">{{category.category_name}} Services</h1>
<div class="service-container">
      <div class="message">{% include 'messages.html' %}</div>
    <div class="search-div mb-5">
        <input type="text" id="search-input" placeholder="search">
        <button class="btn btn-primary service-search-btn " type="button">Search</button>
    </div>
    <div class="service-list p-1" id="service-list" style="min-height:60vh;">
        {% for i in category.service_set.all %}
        <div class="service-list-card mb-4 p-2" data-aos="fade-right"  data-aos-delay="150"
    data-aos-duration="1000">
            <div class="card-inner-container">
                <div class="card-div1">
                    <img src="/{{i.image}}"
                         alt="">
                </div>
                <div class="card-details">
                    <p class="service-name">{{i.service_name}}</p>
                    <p class="session">{{i.session_time}}min</p>
                    <p class="service-cost text-success">Rs.{{i.session_cost}}</p>
                    <p class="service-desc">{{i.service_description}}</p>

                </div>
            </div>
            <div class="actions-div">
                <a href="/users/add_to_wishlist/{{i.id}}/{{category.id}}"
                   onclick="return confirm('Are you sure you want to add this service to wishlist?')"
                   class="btn btn-sm btn-primary add-btn">Add</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class=" feedback-container p-2 mt-5 mb-5" >
        <h2 class="head-text text-center mt-5 mb-5" data-aos="fade-down"  data-aos-delay="50"
    data-aos-duration="500">Feedbacks</h2>

        <div class="feedback-btn-div text-center mb-4">
            <a href="/users/post_feedback/{{category.id}}" class="btn btn-primary ">Post Feedback</a>
        </div>
        <div class="feedback-list p-2">
            {% for i in feedbacks %}
            <div class="feedback-list-card  mb-5" data-aos="flip-up"  data-aos-delay="350"
    data-aos-duration="500">
                <img class="user-profile-img"
                     src="/{{i.user.profile.profile_pic}}"
                     alt="">
                <div class="user-details">
                    <div class="feedback-info mb-2">
                        <span class="user-name">{{i.user.username}}</span> {{i.added_date}} <br>
                        Rating: <span class="rating-no">{{i.rating}}</span> /10
                    </div>
                    <div class="feedback-text p-3">
                        {{i.feedback}}
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}